### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & FadeProps'.

### ISSUE THREAD

**Issue by RustyNova016** [morellodev/react-awesome-reveal#119]
![image](https://user-images.githubusercontent.com/50844553/166980935-32814a47-9a07-46d5-8b85-1d3b469e9182.png)

My IDE thinks you can't put a children inside a Fade component, but it still works regardless

**Comment by morellodev** [comment]
Are you using React 18? The `children` prop is missing from the `React.FC` type definition for React 18, I have to release a new version of the library that is 100% compatible with the new React version.

**Comment by RustyNova016** [comment]
Yeah it's react 18.1 along Next.js. Thankfully it still works for now.

**Comment by morellodev** [comment]
This is an issue affecting only the type definitions, not the components behavior at runtime with React 18.

**Comment by morellodev** [comment]
A new preview release is out, please upgrade to v4 beta by running:

```sh
yarn add react-awesome-reveal@next @emotion/react
```

Please note that from version 4 the `@emotion/react` dependency must be explicitly installed (it is now a peer dependency of RAR).
