### ISSUE TITLE
Flex:1 is ignored 

### ISSUE THREAD

**Issue by issimissimo** [morellodev/react-awesome-reveal#129]
If you create a Reveal component, and you create inside it a div with a classname="flex-1" (I'm using Tailwind), this CSS property (flex:1) will be ignored.
The only solution that I've found is to create the div first (with classname="flex-1"), and next put all the others elements after the Reveal component.
It's not the best, since you can have issues later on

**Comment by morellodev** [comment]
Would you mind creating a Codesandbox reproduction of the issue?
