### ISSUE TITLE
Failed to parse source map for multiple files

### ISSUE THREAD

**Issue by howardleejh** [morellodev/react-awesome-reveal#131]
I'm using the latest versions of react and came across multiple "Failed to parse source map from ..."  when using React Awesome Reveal. Was wondering if there's a fix to this? Current version of repo:

- React ^18.2.0
- React Scripts ^5.0.1
- React Dom ^18.2.0

**Comment by morellodev** [comment]
Could you reproduce the issue on Codesandbox?

**Comment by howardleejh** [comment]
It seems like the missing source maps are not appearing on CodeSandBox. But it appears on my local dev environment.

**Comment by morellodev** [comment]
If the issue is not deterministically reproducible, it is likely an issue with your env rather than with the lib itself. Which Node version (and package manager) are you using?

**Comment by howardleejh** [comment]
I'm currently using node v18.4.0 and npm v8.12.1.
