### ISSUE TITLE
Add feature to play animation on condition

### ISSUE THREAD

**Issue by Retch** [morellodev/react-awesome-reveal#135]
maybe add a disabled tag which can be manipulated to play when state changes.

**Comment by Retch** [comment]
maybe add a disabled tag which can be manipulated to play when state changes.

**Comment by Upbolt** [comment]
i made a little wrapper component that you can use as well

```tsx
import { Fade as DefaultFade, FadeProps } from "react-awesome-reveal";

interface Props extends FadeProps {
	disabled?: boolean;
}

export default function Fade(props: Props) {
	if (!props.disabled) {
		return <DefaultFade {...props} />;
	} else {
		return <>{props.children}</>;
	}
}
```

hope it helps

**Comment by morellodev** [comment]
This feature is outside the scope of the library (the only condition that triggers an animation is the visibility in the viewport).
