### ISSUE TITLE
Fade component duplicates parent element

### ISSUE THREAD

**Issue by DoomyCrystal** [morellodev/react-awesome-reveal#140]
I'd like to animate the children elements inside this grid container:
```jsx
function ColumnBlock({ blok }) {
  return (
    <Fade cascade className="container grid grid-cols-12 gap-4">
      {blok.columns && blok.columns.map(blok => (
        <div key={blok._uid} className="col-span-12 lg:col-span-5 odd:lg:col-start-2">
          Content
        </div>
      ))}
    </Fade>
  )
}
```
However, the Fade component seems to duplicate the parent element for each child element:
```html
<div class="container grid grid-cols-12 gap-4 css-zyscma" style="animation-delay: 0ms;">
  <div class="col-span-12 lg:col-span-5 odd:lg:col-start-2">Content</div>
</div>
<div class="container grid grid-cols-12 gap-4 css-sanqhm" style="animation-delay: 500ms;">
  <div class="col-span-12 lg:col-span-5 odd:lg:col-start-2">Content</div>
</div>
```
When I use any other html tag, there's only one container, but with two children. Why not with Fade?

**Comment by morellodev** [comment]
It is a totally normal behavior, since composition works this way.

I plan to add an `as` prop to change the element rendered by an animated component; in the meanwhile, you can refer to this [CodeSandbox example](https://codesandbox.io/s/busy-alex-jv50jp?file=/src/App.tsx) to achieve your intent.

**Comment by DoomyCrystal** [comment]
Awesome, now it's working. Thanks a lot for the example!
