### ISSUE TITLE
Cannot use package

### ISSUE THREAD

**Issue by jakebooy2** [morellodev/react-awesome-reveal#147]
Whenever I import any of the elements from this package, I get this error:

./node_modules/react-awesome-reveal/dist/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)

**Comment by morellodev** [comment]
Sorry Jake,

I need a reproducible example of the issue with the details about your environment.

Follow the guidelines for opening an issue, thanks.

**Comment by Viskazz** [comment]
Same here. I'm just updated to v.4.1.0 from 3.3.2. Will return if can reproduce

**Comment by Satosh-J** [comment]
I updated to 4.3.2 but I got this error too.
```
./node_modules/react-awesome-reveal/dist/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

**Comment by morellodev** [comment]
I need a reproducible example of the issue with the details about your environment.

Follow the guidelines, thanks.

**Comment by Skazio** [comment]
Hey @morellodev I've got the same problem
Would this help you ?

https://github.com/Skazio/react-awesome-reveal-bug

**Comment by morellodev** [comment]
I see you are using an older version of `react-scripts`. Either update it to a more recent version (`react-scripts@^5`) or use other build tools like [Vite](https://vitejs.dev).
