### ISSUE TITLE
Flickering transition when upgrading to 4.2.0

### ISSUE THREAD

**Issue by pgrodrigues** [morellodev/react-awesome-reveal#165]
**Describe the bug**
There is a brief flickering, where the  element associated with a transition is made visible, right before the transition takes place.

My use case is a bit more complex due to the use of MUI's useScrollTrigger hook, but managed to simplify it in the Codesandbox below. This started to happening when upgrading to 4.2.0, Using 4.1.0 seems ok.

**To Reproduce**
1. Open this [CodeSandbox](https://codesandbox.io/s/condescending-tamas-6foowi);
2. Scroll from top to bottom slowly until the "ANIMATED HEADER" is displayed;
3. It will flicker briefly before the transition happens.

**Expected behavior**
It should not flicker.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 4.2.0

**Comment by morellodev** [comment]
Hi, please update to the latest version (v4.2.3 at the time of writing this).

However, I see you are using the `useScrollTrigger` hook from `"@mui/material"` and then you conditionally render the animated header. This causes a layout shift and it is not necessary – if you want to control how much the element should be in the viewport before triggering the animation, you can use the [`fraction`](https://react-awesome-reveal.morello.dev/docs/revealing-effects#fraction) prop.

**Comment by pgrodrigues** [comment]
Hey @morellodev, thanks for the feedback. Using 4.2.3 still causes the same effect. I don't think fraction prop is applicable here as the component is being conditionally rendered due to a requirement. Eitherway, given that conditional rendering is messing up with the revealing animation I will just use the regular MUI transition for this specific case.
