### ISSUE TITLE
Add support for prefers-reduced-motion

### ISSUE THREAD

**Issue by rickyhaswifi** [morellodev/react-awesome-reveal#185]
Can we get support for when a user has 'prefers-reduced-motion' on their machine as a prop

<Fade
prefersReducedMotion // optional boolean
>
</Fade>

Maybe it can just return child elements as if it were a fragment or a div. 

Thank you!

**Comment by hckhanh** [comment]
I think it's applied to global styles: https://github.com/search?q=repo%3Amorellodev%2Freact-awesome-reveal%20reduce&type=code

**Comment by morellodev** [comment]
It is already implemented, closing this
