### ISSUE TITLE
Animations not working when I bump the project to Next 14

### ISSUE THREAD

**Issue by MarijaMilovanovic** [morellodev/react-awesome-reveal#191]
Everything worked for me with "next": "13.4.8", but when I bumped next version to 14 and updated the package it doesn't work, for example text that should fade in stays at opacity 0. I'm using client components in app router.

**Comment by DMOEdetc** [comment]
Duplicated Issue: https://github.com/morellodev/react-awesome-reveal/issues/186

**Comment by zulqarnain1231** [comment]
yes i am also facing same issue any solution for this

**Comment by morellodev** [comment]
Fixed in [version 4.2.7](https://github.com/morellodev/react-awesome-reveal/releases/tag/react-awesome-reveal%404.2.7)
