### ISSUE TITLE
SSR implementation for crawlers?

### ISSUE THREAD

**Issue by albertcarrete** [morellodev/react-awesome-reveal#50]
One of the promoted features is that this works out of the box with SSR. I took that to mean that when javascript is off the components will still be visible so that crawlers can read the page. If that assumption is incorrect then skip the rest.

I followed the documentation, animation works great.
``` javascript
<Fade>
    <div>My content</div>
</Fade>
```
but when I turn off javascript the component remains in a hidden state. 

In order to circumvent this, I added a class to the Fade component.

``` javascript
<Fade className="animated-element">
    <div>My content</div>
</Fade>
```

and made it visible when there is no javascript.

```html
<noscript>
    <style type="text/css">
        .animated-element{
            opacity:1 !important; 
        }
    </style>
</noscript>
```
 Works great but... is this the best solution?

**Comment by dennismorello** [comment]
Hi @albertcarrete, I will definitely check this.

**Comment by HanliTheron** [comment]
Hi @dennismorello, is there maybe any information on the progress on this?

**Comment by emdotem** [comment]
+1

**Comment by kikoanis** [comment]
I am not sure if this is really related to whether SEO can crawl hidden DOM elements or not and correct me if I am wrong. The library is about revealing DOM elements when they are in browser view port. My question is what could prevent SEO from crawling such elements if they were hidden by some CSS.

Am I missing anything here?
