### ISSUE TITLE
demo site not showing effects?

### ISSUE THREAD

**Issue by rowe-morehouse** [morellodev/react-awesome-reveal#77]
Is something wrong with your demo site?

https://react-awesome-reveal.morello.dev/docs/pulse

Trying to see the effects … just get large purple buttons for all effects. 

I tried it in 2 different browsers. Not sure if it's me or you.

**Comment by morellodev** [comment]
The demo website is quite old, I am rewriting it using Docusaurus.

**Comment by idindrakusuma** [comment]
Hi @morellodev 
are you still developing the documentation?
I'm still can't show the demo in https://react-awesome-reveal.morello.dev/docs/effects/flip

Can I help for this?

**Comment by morellodev** [comment]
I did not have much time to work on this, but I will definitely improve the docs.
