### ISSUE TITLE
Export component props separately in TypeScript

### ISSUE THREAD

**Issue by nicholaschiang** [morellodev/react-awesome-reveal#79]
Currently, you're only exporting the component types from `dist/index.d.ts`. Could you also export the component prop types?

For example, I'm trying to use Next.js [`dynamic`](https://nextjs.org/docs/advanced-features/dynamic-import) feature to dynamically import the `Fade` component from this library. But I can't do it in TypeScript without access to the `FadeProps` type:

```tsx
import { FadeProps } from 'react-awesome-reveal';
import dynamic from 'next/dynamic';

const Fade = dynamic<FadeProps>(
  () => import('react-awesome-reveal').then((m) => m.Fade),
  () => { loading: '...' }
);
```

**Comment by morellodev** [comment]
+1 for this, I will release a new version with prop types export.

For simpler use cases, this built-in utility type coming from React can be used today:

`type FadeProps = React.ComponentProps<typeof Fade> `

**Comment by morellodev** [comment]
The feature has been merged into `develop` and will be released in the next major release (v4).
