### ISSUE TITLE
Is it possible to wrap component with Fragment, without additional div?

### ISSUE THREAD

**Issue by evgeny-s** [morellodev/react-awesome-reveal#82]
See question in topic.
Thanks!

**Comment by morellodev** [comment]
Yes, you can!

**Comment by evgeny-s** [comment]
How can I do this? 
Could you please share some option or prop to achieve this? 
Thanks!

**Comment by evgeny-s** [comment]
I've provided `className` for the container, but now it turns all children to be animated separately, but I need to have only parent element animated.
