### ISSUE TITLE
"delay" prop is not counting on milliseconds.

### ISSUE THREAD

**Issue by LureDev** [morellodev/react-awesome-reveal#84]
Something is wrong with the `delay` prop. It's not counting the delay by milliseconds (at least on the `Fade` element).
If i pass `delay="1000"`, it will take 10 seconds to run the animation, but the correct would be 1 second, since 1000 milliseconds is 1 second, right? But if i pass `delay="100"`, then it takes 1 second to run the animation.

This is my code, if you need to take a look:
```   
<Fade delay="1000">
      <section className="listBox">
        <PeopleList />
        <div style={{ width: "100%", textAlign: "center" }}>
          <button>Clear all</button>
        </div>
      </section>
</Fade>
```

**Comment by morellodev** [comment]
The `delay` prop must be passed as a number, not as a string.

**Comment by LureDev** [comment]
Ooh, sure. I'm sorry about it xD, it's working correctly now with number values.
