### ISSUE TITLE
triggerOnce true by default

### ISSUE THREAD

**Issue by CodaBool** [morellodev/react-awesome-reveal#87]
# background
this is an awesome library, was using react-reveal but is currently as of 8/2021 breaking on newest React requiring a force install. 

# Discussion
I tested a few modules and they usually have a fade in to happen once by default. I think this would be the most common use case and should be set that same way here. What would be your thoughts on changing this to default true?

**Comment by adstr123** [comment]
I think most use cases would have `triggerOnce` set as true (certainly the sites I seem to browse/develop prefer this). But given that this would be a significant breaking change, I don't think it's worth it. Suddenly, all the sites currently using this library without having specified a `triggerOnce` value (and therefore leaving it as the default `false`) would have their behaviour changed.

**Comment by CodaBool** [comment]
👍  fair enough. I'll close this up
