### ISSUE TITLE
Animation lag with large components 

### ISSUE THREAD

**Issue by Senty11** [morellodev/react-awesome-reveal#91]
Hello! I'm using react-awesome-reveal for a project and it seems on mobile phones it's lagging when used with large image components. On PC though it works fine. Any suggestions?

Here's a code preview and video of the lag:

> return (
>     
>     <div id ="roadmap">
>       <Slide direction="right">
>       <Image width='700px' height='1678px' alt='roadmap'/>
>       </Slide>
>       </div>
>       
>   );

https://user-images.githubusercontent.com/52800564/134001691-ff562536-9778-486e-8846-bf33ab135805.mp4

**Comment by sshmaxime** [comment]
have you figure out what's up ? @Senty11
