### ISSUE TITLE
TypeError: Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by federicocappellotto97** [morellodev/react-awesome-reveal#98]
I'm using next@12.0.3 and react-awesome-reveal@3.8.1
Why am I getting this error?
`TypeError: Cannot read property 'css' of undefined`

<img width="804" alt="Schermata 2021-11-14 alle 14 32 53" src="https://user-images.githubusercontent.com/63153191/141683363-05a678b2-6629-4355-9e8f-1db0cb477aaa.png">

This is how i'm using it:
`import { Fade } from 'react-awesome-reveal'`
`<Fade direction="down" duration={1500} delay={300} triggerOnce>
     <span>Lorem ipsum</span>
</Fade>`

**Comment by morellodev** [comment]
A new preview release is out, please upgrade to v4 beta by running:

```sh
yarn add react-awesome-reveal@next @emotion/react
```

Please note that from version 4 the `@emotion/react` dependency must be explicitly installed (it is now a peer dependency of RAR).
